version: '3.7'

services:
  db:
    container_name: db-container
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - app

volumes:
  db_data:
